# Generated by Django 4.2.7 on 2025-11-02 18:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Clothing", "Clothing"),
                            ("Books", "Books"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of image URLs"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of tags"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product specifications and attributes",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("comment", models.TextField()),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_sku_fe2039_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_categor_417272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured"], name="products_is_acti_d79db5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_price_fe467e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_created_a77fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_brand_b2547a_idx"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "-created_at"], name="product_rev_product_b958dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["is_approved"], name="product_rev_is_appr_dbd189_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="categories_is_acti_aae090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="categories_name_98d7d5_idx"),
        ),
    ]
