# Generated by Django 4.2.7 on 2025-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Product specifications and attributes",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of image URLs", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of tags", null=True
            ),
        ),
    ]
