# Generated by Django 4.2.7 on 2025-11-02 19:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_attributes_alter_product_images_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField(help_text="Image URL", max_length=500)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for image",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("position", models.IntegerField(default=0, help_text="Display order")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary product image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_images",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
            },
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="idx_product_sku",
            old_name="products_sku_fe2039_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="idx_category_active",
            old_name="products_categor_417272_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="idx_active_featured",
            old_name="products_is_acti_d79db5_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="idx_product_price",
            old_name="products_price_fe467e_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="idx_created_at",
            old_name="products_created_a77fb9_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="idx_product_brand",
            old_name="products_brand_b2547a_idx",
        ),
        migrations.RenameIndex(
            model_name="productreview",
            new_name="idx_review_product",
            old_name="product_rev_product_b958dd_idx",
        ),
        migrations.RenameIndex(
            model_name="productreview",
            new_name="idx_review_approved",
            old_name="product_rev_is_appr_dbd189_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price (for showing discounts)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dimensions: {length, width, height} in cm",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Primary product image URL",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(default=False, help_text="Bestseller flag"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, help_text="New arrival flag"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keywords",
            field=models.TextField(blank=True, help_text="SEO keywords", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="model_number",
            field=models.CharField(
                blank=True, help_text="Model/part number", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="helpful_count",
            field=models.IntegerField(
                default=0, help_text="Number of users who found this helpful"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom product attributes (color, size, specifications)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Product brand/manufacturer",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Books", "Books"),
                ],
                db_index=True,
                help_text="Product category: Electronics, Clothing, or Books",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Product cost price (for margin calculation)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed product description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of additional image URLs"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether the product is currently active/available",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Product availability status"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Featured product (shown prominently)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="low_stock_threshold",
            field=models.IntegerField(
                default=10,
                help_text="Alert threshold for low stock",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, help_text="SEO meta title", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Product name (e.g., Prod1)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Product selling price",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(
                help_text="Unique product identifier from CSV",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Brief product description for listings",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                db_index=True,
                help_text="Stock Keeping Unit (e.g., SKU0001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly product identifier",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(
                default=0,
                help_text="Current stock quantity",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Product tags for categorization and search",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="comment",
            field=models.TextField(help_text="Review comment/description"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="customer_email",
            field=models.EmailField(help_text="Customer email", max_length=254),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="customer_name",
            field=models.CharField(help_text="Customer name", max_length=200),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="is_approved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the review is approved for display",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="is_verified_purchase",
            field=models.BooleanField(
                default=False, help_text="Whether this is from a verified purchase"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                help_text="Rating from 1 to 5 stars",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="title",
            field=models.CharField(help_text="Review title/headline", max_length=200),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="idx_product_name"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["rating"], name="idx_review_rating"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="catalog.product",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "position"], name="idx_image_product"
            ),
        ),
    ]
