# Generated by Django 4.2.7 on 2025-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productimage_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom product attributes (color, size, specifications)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of additional image URLs",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly product identifier",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Product tags for categorization and search",
                null=True,
            ),
        ),
    ]
