# Generated by Django 4.2.7 on 2025-11-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_attributes_alter_product_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
    ]
