# Generated by Django 4.2.7 on 2025-11-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_product_dimensions_remove_product_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="idx_active_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_bestseller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_new",
        ),
        migrations.RemoveField(
            model_name="product",
            name="low_stock_threshold",
        ),
    ]
